spring:
  application:
    name: image

server:
  port: 9993

eureka:
  client:
    serviceUrl:
#      defaultZone: https://user:ieX6ooF1@guarded-plateau-9108.herokuapp.com/eureka/
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
#  instance:
#    appname: IMAGE
#    metadataMap:
#      instanceId: IMAGE:${spring.application.instance_id:${random.value}}
