server:
  port: 9991

spring:
  application:
    name: bird-mainpage-service

eureka:
  client:
    serviceUrl:
      defaultZone: https://user:ieX6ooF1@guarded-plateau-9108.herokuapp.com/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
  instance:
    appname: MAINPAGE
    metadataMap:
      instanceId: MAINPAGE:${spring.application.instance_id:${random.value}}